### ISSUE TITLE
Colormath 3.0.0 build 1 is broken

### ISSUE THREAD

**Issue by ewels** [conda-forge/colormath-feedstock#5]
Hi @conda-forge/core,

I'm new to the software packaging game and I managed to accidentally push a broken release of `colormath` to conda-forge. This is now causing difficulties with the installation of downstream tools.

@mbargull advises me that marking the `colormath=3.0.0=*_1` builds as broken on conda-forge should clear all of this up. Is it possible for one of the esteemed core team members to help us with this please? Hopefully then installations will take the later build numbers instead, which should make everything work again.

Many thanks 🙇 

Phil

**Comment by ocefpaf** [comment]
@ewels  can you double check if I got it correctly?

https://anaconda.org/conda-forge/colormath/files?version=3.0.0

**Comment by mbargull** [comment]
Perfect, thanks @ocefpaf!

**Comment by ocefpaf** [comment]
BTW, sometimes we, conda-forge core members, miss the notifications on specific feedstocks. It is more "efficient" to post issues like this on gitter for better visibility.

**Comment by ewels** [comment]
Fantastic stuff, many thanks for the super fast response @ocefpaf!
